public class Message {

    private static char[] alphabets = new char[] {'A', 'B', 'C', 'D', 'E', 'F', 'G','H','I','J','K','L','M','N','O','P','Q', 'R', 'S', 'T', 'U', 'V','W','X','Y','Z'};

    public static void main(String[] args) {
        String message = "OVZCZGDDPOOSJBNKNFZMVZGOYPTZGOOYVBYKNJDFDRGIVQOOYIKYIPTMJFOOUVVFZOXYHAJXVBYSIHZBZGOSIUPXYSMVTWIQGCBSXBJDDQZDCOODCSNYGRDOMGVBZBJDHCOSQOOOYHJBZHMOVHEENHJBZJZXHODXGMWIOVZSMFVDDCIKGONCZGNWZBOYAHCOYOIQZFNYAPVDOZZKIRWIOVZSMGZVAWIDZFZCOFVDCSMDCSTNDGXYQSMKNCPXYFZKNCIDJFPXVKVIWMMOVZDJDBBDCOOGCOOSOAVUZGNOIGZPJFORZAOYYCYOKSINNCIGCOOSOKDVGAVUZGZXNSAYMCORZFNDJRJKIRORVHVVGCADCSJDCSMCXOIXJHDMZHCSNHJYZJZXVEPSOSWBVJZCJZYSZFHKTDMOASMDJFPXMOORZFORVBCOMCDMVZGIWIOZJWIDGSNCGMYSZHMIDBBDJGOOHHCOJBXYHWIQOWYOVZGLTVDWNSGPOVPCRSXYPZYSHOBSISRSOVJEOQJXOFVNDQOSJBVMDFXEHGOKIQZSIKCSXVVXVFHIVZGYAKCYNSHOHPZBNOMOWFVFZTGOZGVDOCKCKSZNWSAYMSORZSIOHMHKFSNKHCQODTORZGJVYWZBNFZKGZTKMSWBVJZDCSIDCWNCPFZVTWNXOHCOJIOMJAZKIMJPOVZWROIDZRZKXVRYPZYRVJZZMSAOMFZNOVVDVZGCOOINVBYPDUCDRVVDRSCKQSCOMSORZBDCVQVCZWIGCWXROVZSIHZBVQOSJBJPHOIIDBYSQWYEVZGIMOOSJBVVYSXSNWJXHOFSIUKBJQZCNSNYISKBJQZCNDZBNCGNDSMZMCYEXSNKICPDXCHODBOOIRZNWMIYJBZWJGOKMADONHMIOCVFJWYDCWNZMCWVZAEENHVCXCMDZNYSYGDXXSORZMXKIHPCPOGVTAVUZFZDMSVDKVTCDQVVGMDWKCNCDPGOOVZIHOFODHZMJBJWDQVVGMDWKCNCDPGOOVZINVJYORZCZFOOMGORZBNDVBYSIUVXYTDQCHDXBWNOVQCCJZYSZFNSIRDFDRPKGZTBVHDYIOGMJIMCZCAKXHDYIOADZFVVGPZMVINOOVZMJGOYAFPXIWIQDGNEMSOYWSVDGSVCOONRDUCKNHCOXCNDJTNDVMDXB";
        char[] charArray = message.toCharArray();
        decrypt(charArray, new int[]{21, 14, 21, 10});
    }

    public static void decrypt(char[] messageStr, int[] keys)
    {
        int keyLen = keys.length;
        String detectedString = "";
        int i = 0;

        for (char str: messageStr) {
            if (i == keyLen) i = 0;
            int cipherPos = new String(alphabets).indexOf(str);
            int modulo = getModulo(cipherPos - keys[i]);
            detectedString +=  alphabets[modulo];
            i++;
        }
        System.out.println(detectedString);
    }

    public static int getModulo(int value)
    {
        if (value < 0) {
            value = 26 + value;
        }
        return value % 26;
    }
}
